### ISSUE TITLE
发送问题后，没有回复，如何解决?chatgpt说时网络问题。

### ISSUE THREAD

**Issue by fengyunzaidushi** [postor/chatpdf-minimal-demo#2]
`openai.error.APIConnectionError: Error communicating with OpenAI: 
HTTPSConnectionPool(host='api.openai.com', port=443): 
Max retries exceeded with url: /v1/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x70a2dfd4d430>: 
Failed to establish a new connection: [Errno 110] Operation timed out'))`

> 这个错误信息提示了在使用 OpenAI API 连接时出现了错误，并且似乎是由于连接超时而导致的。可能的原因是网络问题，或者 OpenAI 服务器出现了问题。

以下是一些您可以尝试的解决方法：

检查网络连接：请确保您的计算机已连接到互联网，并且可以访问其他网站。如果您使用的是 VPN 或代理服务器，请尝试暂时禁用它们，然后再次运行代码。

检查 OpenAI 服务器状态：请访问 OpenAI 网站并检查是否有任何公告或通知。如果 OpenAI 服务器出现了问题，您可能需要等待一段时间，然后再次尝试。

增加连接超时时间：如果您的网络连接较慢或不稳定，可能需要增加连接超时时间。您可以通过设置 timeout 参数来实现这一点，例如：
`
import openai
openai.api_key = "YOUR_API_KEY"
response = openai.Embedding.create(engine="davinci", text="Hello, world!", timeout=30)

`

请问你是如何解决的？谢谢！

**Comment by postor** [comment]
目测是被墙了，你后台服务没翻墙，最简单的办法是买个境外主机启动服务，或者复杂点自己搭梯子全局代理
