### ISSUE TITLE
how to generate question automatically?

### ISSUE THREAD

**Issue by hktxt** [postor/chatpdf-minimal-demo#3]
we can split articles into pieces and then convert them to embeddings using openAI.
However, how can we generate questions automatically?
we only have articles, we don't have questions. manually write?

**Comment by postor** [comment]
That just need a little more logic, you can give ChatGPT some part of the content as context and ask him for questions. For more resonable questions, you will need to sample more content like a chapter or two and group them with clustering, then sample from each group to ask ChatGPT for questions

**Comment by postor** [comment]
@hktxt added example code to generate question now
